const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

const UPLOADS_DIR = path.join(__dirname, "..", "..", "uploads", "converted");

// Ensure output directory exists
if (!fs.existsSync(UPLOADS_DIR)) {
    fs.mkdirSync(UPLOADS_DIR, { recursive: true });
}

/**
 * Convert plain text content to a PDF file.
 * Returns the relative path to the generated PDF.
 */
exports.textToPdf = async ({ title, content, author }) => {
    return new Promise((resolve, reject) => {
        const filename = `${Date.now()}_${title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 50)}.pdf`;
        const outputPath = path.join(UPLOADS_DIR, filename);
        const relativePath = `/uploads/converted/${filename}`;

        const doc = new PDFDocument({
            size: 'A4',
            margins: { top: 60, bottom: 60, left: 60, right: 60 },
            info: {
                Title: title,
                Author: author || 'ELMS',
                Creator: 'ELMS Document Converter',
            }
        });

        const stream = fs.createWriteStream(outputPath);
        doc.pipe(stream);

        // Header
        doc.fontSize(24)
            .font('Helvetica-Bold')
            .fillColor('#05398F')
            .text(title, { align: 'center' });

        doc.moveDown(0.5);

        // Separator line
        doc.moveTo(60, doc.y)
            .lineTo(535, doc.y)
            .strokeColor('#09AEF5')
            .lineWidth(2)
            .stroke();

        doc.moveDown(0.5);

        // Metadata line
        if (author) {
            doc.fontSize(10)
                .font('Helvetica')
                .fillColor('#666666')
                .text(`Author: ${author}  |  Generated: ${new Date().toLocaleDateString()}`, { align: 'center' });
            doc.moveDown(1);
        }

        // Body text
        doc.fontSize(12)
            .font('Helvetica')
            .fillColor('#333333')
            .text(content, {
                align: 'left',
                lineGap: 4,
                paragraphGap: 8
            });

        // Footer on each page
        doc.on('pageAdded', () => {
            doc.fontSize(8)
                .fillColor('#999999')
                .text('Generated by ELMS', 60, doc.page.height - 40, { align: 'center' });
        });

        doc.end();

        stream.on('finish', () => {
            resolve({
                filename,
                path: relativePath,
                fullPath: outputPath,
                size: fs.statSync(outputPath).size,
            });
        });

        stream.on('error', reject);
    });
};

/**
 * Convert a text/plain file to PDF.
 */
exports.fileToPdf = async (filePath, title) => {
    const absolutePath = filePath.startsWith('/')
        ? path.join(__dirname, '..', '..', filePath)
        : filePath;

    if (!fs.existsSync(absolutePath)) {
        throw new Error(`File not found: ${filePath}`);
    }

    const content = fs.readFileSync(absolutePath, 'utf-8');
    const fileName = title || path.basename(filePath, path.extname(filePath));

    return exports.textToPdf({
        title: fileName,
        content,
        author: 'ELMS File Converter',
    });
};
